name: Tata Sky Daily Workflow
on:
 schedule:
   - cron: "00 21  * * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Daily Loop
      run: |

                       git config --global user.name "rraj1572"
                       git config --global user.email "rishabhpao2012@gmail.com"
                       git clone https://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@github.com/rraj1572/TataSkyIPTV-Daily
                       cd TataSkyIPTV-Daily/
                       git pull https://github.com/ForceGT/Tata-Sky-IPTV || echo "No need to update repo"
                       cd code_samples/
                       chmod 755 *
                       sudo apt-get install expect -y
                       ./script.exp
                       git clone https://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@gist.github.com/0dfc1ce2d8e040dcebc6a55e9744658f
                       rm 0dfc1ce2d8e040dcebc6a55e9744658f/allChannelPlaylist.m3u
                       mv *.m3u 0dfc1ce2d8e040dcebc6a55e9744658f/
                       cd 0dfc1ce2d8e040dcebc6a55e9744658f
                       git add .
                       git commit -m "Playlist has been updated."
                       git push
                       exit